### ISSUE TITLE
JavaScript page does not load

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding.github.io#101]
**Describe the bug**
Upon visiting the page for the JavaScript course, nothing loads.

**To Reproduce**
1. Go to the homepage
2. Click on 'Μάθε JavaScript για να κάνεις την ιστοσελίδα σου λειτουργική'
3. See error

**Expected behavior**
The site would load

**Screenshots**
[Screenshot of the issue](https://i.imgur.com/lBh8kDz.png)

**Desktop:**
 - OS: Linux Mint
 - Browser Firefox
 - Version: 21.2 Cinnamon

**Comment by GalaxyGamingBoy** [comment]
I would appreciate attaching the logs

**Comment by odysseuskir** [comment]
Vercel says this is an error 500 when trying to get `/lessons/view/javascript/`. I am attaching the logs provided by Vercel below.

```
07:28:49 AM [ssr] TypeError: Cannot read properties of undefined (reading 'icon')
    at Object.default (file:///var/task/dist/chunks/pages/index.astro.70d1ff66.mjs:448:51)
    at new AstroComponentInstance (file:///var/task/dist/chunks/astro.7743419c.mjs:1702:32)
    at createAstroComponentInstance (file:///var/task/dist/chunks/astro.7743419c.mjs:1739:20)
    at renderComponent (file:///var/task/dist/chunks/astro.7743419c.mjs:2697:12)
    at file:///var/task/dist/chunks/pages/index.astro.70d1ff66.mjs:442:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async renderPage$1 (file:///var/task/dist/chunks/astro.7743419c.mjs:2850:30)
    at async renderPage (file:///var/task/dist/chunks/astro.7743419c.mjs:4093:18)
    at async #renderPage (file:///var/task/dist/chunks/astro.7743419c.mjs:4461:20)
    at async App.render (file:///var/task/dist/chunks/astro.7743419c.mjs:4359:22) (x3)
```

**Comment by GalaxyGamingBoy** [comment]
Fixed, deployment will begin when [cookie-madness](https://github.com/simplified-coding/simplified-coding.github.io/tree/cookie-madness) hits production aka soon.

**Comment by odysseuskir** [comment]
Great, thanks!
